package-lock.json, pages/_app.js, pages/index.js, src/components/Countdown.js, src/components/Navbar.js, src/components/modal/ModalConfirm.js, src/hooks/useCountdown.js, src/pages/home/index.js, src/theme/GlobalStyle.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=a8d6e98a5b964eb8b6a6f3e2da095aaa
=> added countdown component

.env.example
=> updated .env.example with storageUrl

src/components/Navbar.js
=> navbar fix z-index

pages/recovery/index.js, src/pages/forgot-password/index.js, src/pages/login/index.js
Reset password page
Adding spin to login
https://www.notion.so/ebombo/Dailies-Producto-Tech-f3138494e45c4267992fdd9a23b1641b?p=da912491e4c149c68065badce8db8b05
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=67eac93a40914db5a1515b6cc3ae66a8
=> Reset password

src/pages/admin/coupons/CouponForm.js, src/theme/GlobalStyle.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=01bd01ce9cad4e41a503f880f457e11b
=> added datetime

src/components/Navbar.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=aec165b8660f47c8a7d38552ec674191
=> Making the navbar sticky and bigger for mobile

src/pages/buy-tickets/index.js
https://www.notion.so/ebombo/8-en-la-seccion-de-pago-agregar-informacion-del-certificad-a5e3069eab474e23967476935bd59bc9
=> 8) en la seccion de pago agregar informacion del certificad

src/components/Countdown.js, src/components/Footer.js, src/components/common/DataList.js, src/pages/exhibitors/index.js, src/pages/timeline/index.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8
=> Feedback/comments 09.05

src/components/form/Select.js, src/pages/register/StudentRegister.js, src/pages/register/VisitorRegister.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=e91e025368b9471cbb2af60b415342ca
=> Adding country to register

src/pages/exhibitors/index.js, src/pages/timeline/index.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=45702d598e8146b8a71cbc9f7b79d52a
=> updated bg

src/components/Footer.js, src/pages/home/PreviewCarousel.js
https://www.notion.so/ebombo/TDD-Comentarios-09-05-b94be2c9f9004771a86f8c0596350e84
https://www.notion.so/ebombo/TDD-Comentarios-04-05-05-05-71fbeb90c9c74fe4881747b2f5485dea
=> Rework feedbacks

src/components/Countdown.js, src/components/Sponsors.js, src/components/common/DataList.js
https://www.notion.so/ebombo/TDD-Nuevo-coorganizador-8c39c9a62ec04692ae0343341d3a7bb2
=> adding new sponsor

src/pages/exhibitors/index.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=ec6600503b754752adbf9cec34de1497
Y fix en filtro de expositores
=> fix layout exhibitors && fix filter search

src/components/common/DataList.js, src/pages/content/VideoList.js, src/pages/content/index.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=f683145430ba4660825e75f2f8817f2d
=> added videos && content redesign

src/pages/exhibitors/index.js
=> updated limit size

functions/api/users/post/postUser.js, functions/collections/settings/index.js, functions/config/config.json, functions/email/sendEmail.js, package.json, src/firebase/config.js
https://www.notion.so/ebombo/Dailies-Producto-Tech-f3138494e45c4267992fdd9a23b1641b?p=51f4a74a6c644b9185121e7cdf88d625
=> Send welcome email to user

package-lock.json, package.json, src/pages/admin/users/index.js
https://www.notion.so/ebombo/Descargar-lista-de-usuarios-registrados-formato-CSV-704261c91b2642678fee8a3e7f2e96c3
=> download all users

functions/api/emails/post/postEmail.js, functions/config/config.json
https://www.notion.so/ebombo/Email-de-contactanos-eed18d1ffd214a33acfcb63f2993b9db
=> contact form email

functions/api/users/post/postPayment.js
=> Fixing email event date

src/components/Sponsors.js, src/components/common/DataList.js, src/pages/home/index.js
https://www.notion.so/ebombo/TDD-Nuevo-logo-Coorganizador-UNI-aa4117176b414154b47cd5fe80b2edc0
https://www.notion.so/ebombo/TDD-Centrar-coorganizadores-e2413bef32a84c18bf5e7dbe55ced741
https://www.notion.so/ebombo/TDD-Agregar-boton-de-programa-abajo-de-expositores-bb6c54f409204d228c7e74dd7ce22bfe
=> Requirements TDD

functions/api/index.js, functions/api/users/delete/deleteUser.js, functions/api/users/delete/index.js, functions/collections/users/index.js, src/pages/admin/users/_userId/index.js
https://www.notion.so/ebombo/Poder-eliminar-el-registro-del-usuario-6051c51a124d48b1a8381df820661fe4
=> be able to delete an account

src/components/Countdown.js, src/components/Navbar.js, src/components/Sponsors.js, src/pages/buy-tickets/index.js, src/pages/content/index.js, src/pages/event-countdown/index.js, src/pages/exhibitors/index.js, src/pages/forgot-password/index.js, src/pages/home/index.js, src/pages/login/index.js, src/pages/register/StudentRegister.js, src/pages/register/VisitorRegister.js, src/pages/register/dataList.js, src/pages/register/index.js, src/pages/register/registrationOptions.js, src/pages/timeline/index.js
https://www.notion.so/ebombo/TDD-Redise-o-de-inicio-y-Registro-83602f51f5ac4006ad530131a4ec5439
https://www.notion.so/ebombo/TDD-Cambiar-el-dise-o-de-compra-d50bc90542c0476db9088dcc838984f8
=> new register design & add countdown on buy ticket form

src/components/common/DataList.js
https://www.notion.so/ebombo/TDD-Actualizar-logo-UNI-93b440cf872844abb5baf0b41baec889
=> new logo uni

src/components/Sponsors.js, src/components/common/DataList.js, src/pages/login/index.js, src/pages/register/index.js
https://www.notion.so/ebombo/TDD-Foto-de-mi-Jorgue-Aguinaga-ab37813309bf45f195ee4418b30568e4
https://www.notion.so/ebombo/TDD-Bloque-3-cambio-de-hora-51cc0eb9ce2840e1bb98947724c15800
https://www.notion.so/ebombo/TDD-Nueva-foto-de-Jaime-Dupuy-bd35112ebbda4ed9b49df465c062132e
https://www.notion.so/ebombo/TDD-Cambio-de-titulo-Bloque-3-e442df1ec4254d1fb2b46e9d99c18a2c
https://www.notion.so/ebombo/TDD-Redise-o-de-inicio-y-Registro-83602f51f5ac4006ad530131a4ec5439
https://www.notion.so/ebombo/TDD-Correcci-n-de-inicio-de-sesi-n-ca2673ab9e734095bf42a2c8691fb142
https://www.notion.so/ebombo/TDD-Agregar-logo-de-ebombo-a-coorganizadores-11d4822d4c9d4371a32eb65e8dc1ea3b
=> some refactorings
